name: 'Coverage Notes'
description: 'Code coverage integration using github notes'
inputs:
  jacoco:
    description: 'Path to Jacoco coverage XML'
    required: true
    default: build/jacoco/test/jacocoTestReport.xml
  parser_version:
    description: 'Parser version'
    required: true
    default: '0.2'
  notes_ref:
    description: 'Notes ref'
    required: true
    default: coverage

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    - shell: bash
      run: download_parser.sh ${{ inputs.parser_version }}
    - name: PR opened
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: coverage-notes --notes-ref ${{ inputs.notes_ref }} -jacoco ${{ inputs.jacoco }} create-commit
    - name: PR opened
      if: github.event.pull_request
      shell: bash
      run: coverage-notes --notes-ref ${{ inputs.notes_ref }} create-pr --pr_number ${{ github.event.number }}
