name: 'Coverage Notes'
description: 'Code coverage integration using github notes'
inputs:
  jacoco:
    description: 'Path to Jacoco coverage XML'
    required: true
    default: build/jacoco/test/jacocoTestReport.xml
  parser_version:
    description: 'Parser version'
    required: true
    default: '0.1.1'
  notes_ref:
    description: 'Notes ref'
    required: true
    default: coverage

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    - shell: bash
      run: download_parser.sh ${{ inputs.parser_version }}
    - shell: bash
      run: coverage-notes --jacoco ${{ inputs.jacoco }} > coverage.txt
    - name: Create issue using REST API
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: create_note.sh ${{ inputs.notes_ref }}
